version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: merakiwedding-nextjs
    restart: always
    networks:
      - meraki-network

  nginx:
    image: nginx:alpine
    container_name: merakiwedding-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public/uploads:/var/www/hieunguyen/data/www/merakiweddingplanner.com:ro
    depends_on:
      - nextjs
    restart: always
    networks:
      - meraki-network

networks:
  meraki-network:
    driver: bridge
